name: Generate Gallery JSON

on:
  push:
    branches:
      - main
    paths:
      - 'images/**'
      - '.github/workflows/generate_json.yml'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Environment Variables
        run: |
          echo "R2_ENDPOINT_URL is set: ${{ env.R2_ENDPOINT_URL != '' }}"
          echo "R2_ACCESS_KEY_ID is set: ${{ env.R2_ACCESS_KEY_ID != '' }}"
          # DO NOT print the secret key!
          echo "R2_BUCKET_NAME is set: ${{ env.R2_BUCKET_NAME != '' }}"
          echo "R2_PUBLIC_BASE_URL is set: ${{ env.R2_PUBLIC_BASE_URL != '' }}"
        env:
          R2_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          R2_PUBLIC_BASE_URL: ${{ secrets.R2_PUBLIC_BASE_URL }}

      - name: Run script to generate JSON
        run: python generate_galleries.py
        env: # Use secrets, DO NOT HARDCODE VALUES HERE!
          R2_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          R2_PUBLIC_BASE_URL: ${{ secrets.R2_PUBLIC_BASE_URL }}

      - name: Commit and push changes
        # 添加 set -e，让脚本在出错时立即停止
        run: |
          set -e 
          
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          echo "--- 开始将文件添加到 Git ---"
          git add images/automotive/ images/portrait/
          git add images/automotive/galleries.json images/portrait/galleries.json images/**/*.json
          
          echo "--- 添加文件后的 Git 状态 ---"
          git status
          
          echo "--- 暂存区的文件差异（显示具体更改） ---"
          # 显示实际差异，不使用 --quiet 以便调试
          git diff --staged || echo "Diff 未发现暂存区的更改。"
          
          echo "--- 检查是否存在用于提交的暂存更改 ---"
          # 直接在 if 条件里进行判断，不单独存储退出代码
          if git diff --staged --quiet; then
            echo "未检测到 JSON 文件有更改。"
          else
            echo "检测到更改，开始提交和推送..."
            git commit -m "Automated: 更新画廊 JSON 文件"
            git push origin main
            echo "提交和推送完成。"
          fi
