        name: Generate Gallery JSON

        on:
          push:
            branches:
              - main # 当推送到 main 分支时触发
            paths:
              - 'images/**' # 或者当 images 目录下的任何文件发生变化时触发
              - '.github/workflows/generate_json.yml' # 当 workflow 文件本身变化时也触发
          workflow_dispatch: # 允许手动触发

        jobs:
          generate:
            runs-on: ubuntu-latest # 在最新的 Ubuntu 环境运行
            permissions:
              contents: write # 需要写入权限来提交更改

            steps:
              - name: Checkout repository
                uses: actions/checkout@v4 # 获取仓库代码

              - name: Set up Python
                uses: actions/setup-python@v5 # 设置 Python 环境
                with:
                  python-version: '3.11' # 可以指定您希望使用的 Python 版本

              - name: Run script to generate JSON
                run: python generate_galleries.py # 运行我们的脚本

              - name: Commit and push changes # 提交并推送 JSON 文件的更改
                run: |
                  git config --global user.name 'github-actions[bot]' # 设置提交者名称
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com' # 设置提交者邮箱
                  git add images/**/*.json images/automotive/galleries.json images/portrait/galleries.json # 添加所有可能更改的 JSON 文件
                  # 检查是否有文件被暂存 (git diff --staged --quiet 返回非0表示有更改)
                  if ! git diff --staged --quiet; then
                    git commit -m "Automated: Update gallery JSON files" # 提交更改
                    git push origin main # 推送到 main 分支
                  else
                    echo "No changes to JSON files detected." # 如果没有更改则打印信息
                  fi
